### PR TITLE
Add ImageHelper Unit Tests

### PR DESCRIPTION
**Pull request by dalalvarun**
Solves #2 
Added the necessary dependencies and wrote unit tests for the necessary functionalities

### CODE REVIEW

**Comment by rob93c** [comment]
Hi @dalalvarun, the issue #2 is already being worked on by @kapilgahlot1998

Anyway, the project is now built with Gradle so your changes wouldn't work

**Comment by rob93c** [comment]
Anyway, I like how you tested the helper class, it was a very nice approach!

**Comment by dalalvarun** [comment]
Okay @rob93c Thanks!

**Comment by rob93c** [comment]
I was thinking that if @kapilgahlot1998 doesn't come up with a solution in a week, I can assign you the issue.
Would you like to keep working on this in the meantime?
In that case you will have to align the code to the current state of the repository, and then perform small adjustments (for instance, we should use camelCase everywhere in Java apart from constants)

**Comment by dalalvarun** [comment]
Yea sure. Please assign it to me. I will fix all the naming issues and will align my code to gradle

**Comment by rob93c** [comment]
Hi @dalalvarun, feel free to reopen the pull request once you manage to fix the conflicts.
I will do my best to review it (and in 3 days I will assign you the ticket, probably)

**Comment by rob93c** [comment]
Do you have any update on this pull request, @dalalvarun?

**Pull request closed without merging**
